// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace GridHub_ML
{
    public partial class ValuePrediction
    {
        /// <summary>
        /// model input class for ValuePrediction.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"Temperature")]
            public float Temperature { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"HourOfDay")]
            public float HourOfDay { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"CloudCoverage")]
            public float CloudCoverage { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"WindSpeed")]
            public float WindSpeed { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"EnergyGenerated")]
            public float EnergyGenerated { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for ValuePrediction.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Temperature")]
            public float Temperature { get; set; }

            [ColumnName(@"HourOfDay")]
            public float HourOfDay { get; set; }

            [ColumnName(@"CloudCoverage")]
            public float CloudCoverage { get; set; }

            [ColumnName(@"WindSpeed")]
            public float WindSpeed { get; set; }

            [ColumnName(@"EnergyGenerated")]
            public float EnergyGenerated { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = @"C:\Users\User\Desktop\GridHub\GridHub.ML\ValuePrediction.mlnet";

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

    }
}
